### ISSUE TITLE
Allow running tests with `nim r`

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/canonical-data-syncer#128]
It would nice to be able to run the test suite without a binary being compiled. This prevents the issues that we had in https://github.com/exercism/canonical-data-syncer/pull/126, where a binary file is produced when running the tests.

Currently, running `nim r --styleCheck:error ./tests/all_tests.nim` will fail as it depends on the `configlet` binary being produced in the `src` dir.

**Comment by ee7** [comment]
There is more than one issue here. Trying address the second:

> Currently, running `nim r --styleCheck:error ./tests/all_tests.nim` will fail as it depends on the `configlet` binary being produced in the `src` dir.

(It actually depends on the `configlet` binary being in the **root** dir).

The current state:
- We want to do end-to-end testing of the `configlet` binary
- We want to run those tests easily in CI, which we do by including the end-to-end testing in the `tests/all_tests.nim` file

We can either:
1. Make `tests/test_binary.nim` run `nimble build` if the `configlet` binary does not exist.
2. Make `tests/test_binary.nim` always run `nimble build` first.
3. Move the end-to-end testing from `tests/all_tests.nim` (renaming that file) to something like `end_to_end_tests.nim`.

I prefer option 2, since otherwise it's easy to make some changes to the source code, but forget to rebuild the binary before local testing.

> It would nice to be able to run the test suite without a binary being compiled. This prevents the issues that we had in #126, where a binary file is produced when running the tests.

If I understand correctly, you propose changing these lines
https://github.com/exercism/canonical-data-syncer/blob/ca137261e6b044f495fcec379db4beefbf669dbb/.github/workflows/tests.yml#L53-L54

to use `nim r`. But that just changes the binary output location during CI - why does that matter? Is it because you want to copy-paste that command to run locally, and that you don't want to see the binary when you run `git status` (or perhaps `git add --all`) later? 

Do you mean "without compiling a `configlet` binary?". An `all_tests` binary always needs to be produced.

**Comment by ErikSchierboom** [comment]
I like option 2 best too. 

> Is it because you want to copy-paste that command to run locally, and that you don't want to see the binary when you run git status (or perhaps git add --all) later?

Precisely this. It is also not uncommon for people to look at the tests workflow to figure out how things work, especially since we don't have much documentation yet. And if we do have the option of not compiling after implementing option 2, why not use it? :)
